# Generated by Django 5.1.7 on 2025-04-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(default='temp_id', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
