# Generated by Django 5.1.7 on 2025-05-11 21:31

import user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_guestbook'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', user.models.CustomUserManager()),
            ],
        ),
    ]
